### ISSUE TITLE
BID PLACED RESERVE PRICE HAS BEEN MET / IT DOES NOT CHANGE 

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#19] opened 2022-05-05 06:26 UTC
-RESERVE price has been met (image 1) when placing a bid but the price hasn't changed , so people cant see what the current bid price is, only on the left box by the HISTORY it also its shown as  crossed.. not sure why...

- auction is finished (image2) and Sergio is still the owner, when supposedly Juan placed a bid higher then the reserve price, so Juan did not end up winning the bid therefore it did not transferred to his wallet....

-When a bid is finished , you should not be able to place a bid.. (there's a "place bid" button (blue button) and its actually a make offer button , coz it works as a make an offer on the creator side ( i have to accept it manually)

![WhatsApp Image 2022-05-04 at 10 46 55 PM](https://user-images.githubusercontent.com/103065410/166869194-fd4c5c8d-92a1-49bb-8a24-063853ef5870.jpeg)

![WhatsApp Image 2022-05-04 at 11 04 01 PM](https://user-images.githubusercontent.com/103065410/166870974-c114509a-5a03-4db4-83ff-e5c7560b5d6f.jpeg)

**Comment by secondl1ght** [comment] 2022-05-05 15:31
This looks like a duplicate of #5 and #6.

**Comment by asoltys** [comment] 2022-05-10 22:35
Fixed, this will show the current bid now instead of the reserve once someone bids

**Closed as completed by asoltys** 2022-05-10 22:35 UTC
Labels: Feature Request
