### ISSUE TITLE
featured experience on demand not show stopper

### ISSUE THREAD

**Issue by cozmosnft** [tokenocean/cozmos#16] opened 2022-05-03 18:19 UTC
We need to be able set the featured experience and it needs to stay fixed to the ones we choose... right now it changes to the last one you upload, also missing the profile pic and there's the black box  above it a bit off centered  and the corners are  sticking out
![WhatsApp Image 2022-05-03 at 11 17 20 AM](https://user-images.githubusercontent.com/103065410/166517236-856dcca9-6fc0-480a-b6bd-615b69bd7c64.jpeg)
t

**Comment by secondl1ght** [comment] 2022-05-06 02:29
@cozmosnft Can you send me this image so I can upload and test? I can't reproduce the black box corners issue. You can send it to me on Slack by posting it in the chat channel. Thanks

**Comment by secondl1ght** [comment] 2022-05-06 02:31
Edit: nevermind - see below.

**Comment by secondl1ght** [comment] 2022-05-06 02:46
@cozmosnft Hey guys, this is ready to go. We can do a call and I can show you how it works, you are able to set a featured experience with a few clicks on the backend. Just message me on Slack to setup a meeting time for this!

**Comment by secondl1ght** [comment] 2022-05-11 01:23
Hey guys, this is shipped now and I just pushed the update for the avatar. I will close this but please open a new issue if you are able to reproduce the black box corner issue. Thanks!

**Closed as completed by secondl1ght** 2022-05-11 01:23 UTC
Labels: enhancement

**Comment by cozmosnft** [comment] 2022-05-11 02:17
Will do!! Thanks guys!! 😊
